Package upgrades: * grunt-browserify from 2.1.4 to 3.2.1 * remapify from 1.4.3 to 1.4.4
This breaks rendr-template with the following on `grunt browserify`:
```
Running "browserify:combine_main_js_files" (browserify) task
>> Error: write after end
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```